#!/usr/bin/env python3
"""Generate firmware/Platform/Src/PinMaps.cpp from STM32duino's PeripheralPins.c.

The Arduino firmware's ADC channels, PWM timer channels and I2C pins come
from the default (non-_ALT, uncommented) entries of these ST-generated tables,
so using the same entries keeps the native port electrically identical.
The tables are by STMicroelectronics under the BSD 3-Clause license.

    python tools/generate_pinmaps.py [path-to-STM32duino-variants/STM32F4xx]
"""
from pathlib import Path
import os
import re
import sys

DEFAULT_VARIANTS = Path(os.environ.get('LOCALAPPDATA', '')) / \
    'Arduino15/packages/STMicroelectronics/hardware/stm32/3.0.0/variants/STM32F4xx'
PARTS = [  # device define, variant folder
    ('STM32F446xx', 'F446Z(C-E)(H-J-T)'),
    ('STM32F407xx', 'F407V(E-G)T_F417V(E-G)T'),
    ('STM32F401xC', 'F401R(B-C-D-E)T'),
]
OUT = Path(__file__).resolve().parent.parent / 'firmware/Platform/Src/PinMaps.cpp'

ENTRY = re.compile(r'^\s*\{(P[A-I]_\d+),\s*(\w+),\s*STM_PIN_DATA(?:_EXT)?\(([^)]*)\)\s*\},')


def table(text, name):
    body = re.search(r'PinMap_' + name + r'\[\]\s*=\s*\{(.*?)\n\};', text, re.S)
    rows = []
    for line in body.group(1).splitlines() if body else []:
        m = ENTRY.match(line)  # skips commented lines and _ALTn pins
        if not m:
            continue
        pin, instance, data = m.group(1), m.group(2), [x.strip() for x in m.group(3).split(',')]
        rows.append((pin.replace('_', ''), instance, data))
    return rows


def emit(part, variant):
    text = (variant / 'PeripheralPins.c').read_text(encoding='utf-8')
    out = [f'#if defined({part})']
    out.append('const AdcPin adcPins[] = {')
    for pin, inst, d in table(text, 'ADC'):
        if inst.startswith('ADC'):
            out.append(f'    {{{pin}, {inst}, {d[3]}}},')
    out.append('};')
    out.append('const TimPin timPins[] = {')
    for pin, inst, d in table(text, 'TIM'):
        out.append(f'    {{{pin}, {inst}, {d[2]}, {d[3]}, {d[4]}}},')
    out.append('};')
    for kind in ('I2C_SDA', 'I2C_SCL'):
        out.append(f'const AfPin {"i2cSdaPins" if kind == "I2C_SDA" else "i2cSclPins"}[] = {{')
        for pin, inst, d in table(text, kind):
            out.append(f'    {{{pin}, {inst}, {d[2]}}},')
        out.append('};')
    out.append(f'#endif // {part}')
    return '\n'.join(out)


def main():
    variants = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_VARIANTS
    parts = '\n\n'.join(emit(part, variants / folder) for part, folder in PARTS)
    OUT.write_text(f'''// Generated by tools/generate_pinmaps.py from STM32duino 3.0.0 PeripheralPins.c
// (STMicroelectronics, BSD 3-Clause). Default entries only: the same peripheral
// mapping the Arduino firmware used. Do not edit; regenerate.
#include "PinMaps.h"

{parts}

#define LIVO_COUNT(a) (sizeof(a) / sizeof((a)[0]))
const size_t adcPinCount = LIVO_COUNT(adcPins);
const size_t timPinCount = LIVO_COUNT(timPins);
const size_t i2cSdaPinCount = LIVO_COUNT(i2cSdaPins);
const size_t i2cSclPinCount = LIVO_COUNT(i2cSclPins);
''', encoding='utf-8', newline='\n')
    print('Wrote', OUT)


if __name__ == '__main__':
    main()
